### ISSUE TITLE
Nautilus misaligment

### ISSUE THREAD

**Issue by WithoutCaps** [vinceliuice/Layan-gtk-theme#1]
I am having a bit of an issue with Nautilus on KDE. (Btw, I use Arch)
Not sure but I guess that Mutter does some magic that makes borders invisible and since I am not using Mutter - that's how it looks on my system.

It might be not possible to fix this by style alone, not sure.

![image](https://user-images.githubusercontent.com/23264966/61602473-52e3f180-ac42-11e9-8cd3-83dc0b61573c.png)

**Comment by WithoutCaps** [comment]
How could this happen to me... I made an issue... There is nowhere to run aside fixing this issue myself :(
https://www.youtube.com/watch?v=y983TDjoglQ

**Comment by vinceliuice** [comment]
Fixed now
