### ISSUE TITLE
tool tips color mismatch

### ISSUE THREAD

**Issue by 0xAliRaza** [vinceliuice/Layan-gtk-theme#2]
In Layan-light and in Layan gtk-3 theme when we hover over something with a title a blank white box appears instead of a proper tooltip. I think the issue is that Tooltip background color and text color are the same. Please fix it.

**Comment by henriquearthur** [comment]
There is a comment on gnome-look by **unheeding** with a workaround for this on Chrome at least:

> Excellent theme! I noticed an issue using the Light variant though. Google Chrome doesn't seem to respect the tooltip.background settings, and shows white text on white background. I fixed it in Chrome by changing color to color: rgba(0, 0, 0, 0.7); but then the tooltips for stuff like Budgie panel were black on black, so I changed the background to white background-color: rgba(255, 255, 255, 0.9); and it is now working nicely for both apps.

**Comment by 0xAliRaza** [comment]
Thanks for writing it down buddy but I don't know what color in chrome he was talking about and how to change it. And also, doesn't matter if I fix it in chrome the issue will still be there. I faced it in VSCode too.
P.S: Such a cool theme thought <3.

**Comment by vinceliuice** [comment]
Could you give a screenshot? @0xAliRaza

**Comment by 0xAliRaza** [comment]
@vinceliuice 
![Screenshot from 2019-09-11 22-56-17](https://user-images.githubusercontent.com/33368198/64722384-d0f8a200-d4e7-11e9-8df6-bc1439eb3d5e.png)
![Screenshot from 2019-09-11 22-56-21](https://user-images.githubusercontent.com/33368198/64722385-d1913880-d4e7-11e9-95a1-0f9877eaebf1.png)
![Screenshot from 2019-09-11 22-57-05](https://user-images.githubusercontent.com/33368198/64722386-d1913880-d4e7-11e9-856c-9f645f1c064c.png)
Have a look at these small white boxes. When I move a cursor over some area which contains tooltip this white box pops up instead of a proper tooltip.

**Comment by 0xAliRaza** [comment]
@vinceliuice is the issue fixed?

**Comment by vinceliuice** [comment]
Not yet, I'm working on it

**Comment by atagulalan** [comment]
Ok, I know it's not pretty, but I solved this by changing **src/_sass/gtk/_common.scss** line 3607

Just change

```
...
tooltip {
  &.background {
    &, &.csd {
      ...
      color: $dark_fg_color
    }
  }
...
```

to

```
...
tooltip {
  &.background {
    &, &.csd {
      ...
      color: if($variant == 'light', $dark_fg_color, $popover_fg)
    }
  }
...
```

and compile SCSS.

**Comment by vinceliuice** [comment]
Thanks @atagulalan for your help, now I fixed this issue!
