### ISSUE TITLE
Some visual bugs on Pop OS

### ISSUE THREAD

**Issue by sandangel** [vinceliuice/Layan-gtk-theme#28]
![image](https://user-images.githubusercontent.com/22189661/91510796-0d035d80-e919-11ea-8c44-9698cf7be3d1.png)

A little space between top bar and window

![image](https://user-images.githubusercontent.com/22189661/91510862-3a500b80-e919-11ea-80d9-3f649937a5e6.png)

No theme for categories in Pop Shop. Perhaps adding support for ElementaryOS would fix this since it's a fork of Elementary OS Shop

**Comment by federicotorrielli** [comment]
+1, the store one is really annoying..
