### ISSUE TITLE
Add GTK4 support

### ISSUE THREAD

**Issue by Saecki** [vinceliuice/Layan-gtk-theme#33]
Are you going to add GTK4 support?

**Comment by vinceliuice** [comment]
Yes, it'll be supported

**Comment by Saecki** [comment]
Thank you!

**Comment by cheesits456** [comment]
when?

**Comment by Saecki** [comment]
There has been gtk4 support since I closed this issue. Maybe the apps you're using are written with libadwaita.

**Comment by cheesits456** [comment]
There's no gtk4 folder in the project root and the theme doesn't affect any gtk4 apps, I don't know how you mean there's gtk4 support

**Comment by Saecki** [comment]
Have a look at `src/gtk`there is a `4.0` folder. Maybe try reinstalling the theme.

**Comment by cheesits456** [comment]
Installed theme from AUR, copied from `/usr/share/themes/` to `~/.themes/`, uninstalled AUR package, then used [this](https://github.com/odziom91/libadwaita-theme-changer) repo to change gtk4 theme.

Not sure why that process is required when other gtk4 themes switch properly when changed from tweaks but at least it works now
