### ISSUE TITLE
GNOME 43 GTK4 Support

### ISSUE THREAD

**Issue by TechXero** [vinceliuice/Layan-gtk-theme#53]
Hello there.. 

As a big fan of the Layan theme, and it being the default in my KDE based distro, any word as to when it will get the update to GNOME 43/GTK4 ? 

Thanks a tone and keep up the amazing work.. ;)

**Comment by h1dd3nsn1p3r** [comment]
1+

**Comment by TechXero** [comment]
There are Gradience presets for Layan-Dark, but a lot of apps are not themed, like Tweaks, among many.. The "Arrows" in app launcher disappear and other "Glitches" needs work.. I can wait as long as it takes for this awesome theme to get the love it so deserves.. I been using it as default in my Distro with **Tela-Circle-Purple-Dark** icons for 2 years now, and I won't quit any time soon !

![Xero] (https://i.imgur.com/hhwWilb.jpg)

**Comment by Neo-29** [comment]
@vinceliuice
Would be nice if you could fix this as you did with whitesur
The config works correctly.

**Comment by vinceliuice** [comment]
Fixed!

**Comment by Neo-29** [comment]
> Fixed!

Not entirely.

Not working with `tweaks`.
Theme not applied

**Comment by vinceliuice** [comment]
Do not run -l with sudo @Neo-29

**Comment by Neo-29** [comment]
> Do not run -l with sudo @Neo-29

I did not 

here's the result

![image](https://github.com/vinceliuice/Layan-gtk-theme/assets/90937180/4bea04b3-548b-44a5-91a4-36ab8f89ffd1)

**Comment by vinceliuice** [comment]
Snap (or flatpak) version apps ?

**Comment by vinceliuice** [comment]
What's your system verison ? @Neo-29

**Comment by Neo-29** [comment]
> What's your system verison ? @Neo-29

Fedora 38 gnome 44 in that case

**Comment by vinceliuice** [comment]
Fixed now @Neo-29

**Comment by Neo-29** [comment]
> Fixed now @Neo-29

I'll have a look tomorrow. Tks for your time and work

**Comment by Neo-29** [comment]
Confirmed working now 👍

@vinceliuice

**Comment by TechXero** [comment]
I am trying [AUR -git pkg](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=layan-gtk-theme-git) with -l added for libadwaita it's not working right what's wrong ?

**Comment by vinceliuice** [comment]
This option can not run with root user because it will link ghe file to root folder

**Comment by TechXero** [comment]
So AUR pkg won't work ? @vinceliuice

**Comment by vinceliuice** [comment]
Unfortunately this option won't  work

**Comment by TechXero** [comment]
Ok so all AUR pkgs with the `-l` flag will not work for GTK4 themes.. From what I understand @vinceliuice

**Comment by vinceliuice** [comment]
AUR pkgs run as root to install apps, so it won't work, it can only work with current user

**Comment by TechXero** [comment]
@vinceliuice Weird that the AUR pkg I customized works fine on KDE though.. 
![KDE](https://i.imgur.com/Fo6WuMe.png)
