### ISSUE TITLE
Weird behaviour of quick setting buttons in system menu

### ISSUE THREAD

**Issue by dvd-alt** [vinceliuice/Layan-gtk-theme#54]
After Gnome 44.1 update, theme bugs in quick menu buttons. Is there a quick fix for this?
![image](https://github.com/vinceliuice/Layan-gtk-theme/assets/133899343/28e32367-4a48-4620-ae70-125e46cb1e5e)

**Comment by vinceliuice** [comment]
Just download the last update and reinstall  it

**Comment by dvd-alt** [comment]
I tried but it looks same way, so i tried on a new VM in a different distro (Fedora 38), still cloning git repo, and it has the same behaviour.
![image](https://github.com/vinceliuice/Layan-gtk-theme/assets/133899343/37734209-7b9b-4cb2-a449-da4fefc7d558)

Love so much this theme 
Thx for your time
