### ISSUE TITLE
Ubuntu 19.10 - Need to update font color in context menus and other windows

### ISSUE THREAD

**Issue by IAmVisco** [vinceliuice/Layan-gtk-theme#6]
After update to dev branch of Ubuntu 19.10 I noticed that some windows and menus have font color that mixes with background color on Layan-dark-solid theme. Not sure if that's Ubuntu issue and will be fixed by stable release (sometime at October 17th) but here's a notice. Screenshots included.

Calendar:
![Calendar](https://user-images.githubusercontent.com/18630605/66291599-f57b4a80-e8ea-11e9-955d-82c847cf4847.png)
Context menu:
![Context menu](https://user-images.githubusercontent.com/18630605/66291770-4be88900-e8eb-11e9-8b67-82f64a4d76fa.png)

**Comment by vinceliuice** [comment]
I'll fix this!

**Comment by vinceliuice** [comment]
You can download from github and try again now

**Comment by IAmVisco** [comment]
Thanks I will check it out tomorrow.

**Comment by IAmVisco** [comment]
Just checked, everything is working fine, thanks!

**Comment by vinceliuice** [comment]
That's all right!
