### ISSUE TITLE
Popup calendar text-color not visible

### ISSUE THREAD

**Issue by Feichtmeier** [vinceliuice/Layan-gtk-theme#9]
Hi there :wave: 
Very nice themes you have there :D 

You have dark popovers in the light theme which need their calendar text-color changed 
![image](https://user-images.githubusercontent.com/15329494/68300156-846fb400-009d-11ea-81ff-24b59fea15df.png)

General problem is that dark popovers in a light theme (trust me, we've been there in Yaru :D)

Best regards!

**Comment by vinceliuice** [comment]
I fixed this, Thanks for your feedback.
